namespace EzioHost.Shared.Helpers;

public static class LanguageHelper
{
    public static List<LanguageInfo> GetSupportedLanguages()
    {
        return new List<LanguageInfo>
        {
            new("auto", "Auto", "Tự động chọn"),
            new("vi", "Vietnamese", "Tiếng Việt"),
            new("en", "English", "English"),
            new("es", "Spanish", "Español"),
            new("de", "German", "Deutsch"),
            new("fr", "French", "Français"),
            new("zh", "Chinese", "中文"),
            new("ja", "Japanese", "日本語"),
            new("ko", "Korean", "한국어"),
            new("pt", "Portuguese", "Português"),
            new("it", "Italian", "Italiano"),
            new("ru", "Russian", "Русский"),
            new("ar", "Arabic", "العربية"),
            new("hi", "Hindi", "हिन्दी"),
            new("th", "Thai", "ไทย"),
            new("id", "Indonesian", "Bahasa Indonesia"),
            new("tr", "Turkish", "Türkçe"),
            new("pl", "Polish", "Polski"),
            new("nl", "Dutch", "Nederlands"),
            new("sv", "Swedish", "Svenska"),
            new("no", "Norwegian", "Norsk"),
            new("da", "Danish", "Dansk"),
            new("fi", "Finnish", "Suomi"),
            new("cs", "Czech", "Čeština"),
            new("hu", "Hungarian", "Magyar"),
            new("ro", "Romanian", "Română"),
            new("uk", "Ukrainian", "Українська"),
            new("el", "Greek", "Ελληνικά"),
            new("he", "Hebrew", "עברית"),
            new("fa", "Persian", "فارسی"),
            new("ur", "Urdu", "اردو"),
            new("bn", "Bengali", "বাংলা"),
            new("ta", "Tamil", "தமிழ்"),
            new("te", "Telugu", "తెలుగు"),
            new("ml", "Malayalam", "മലയാളം"),
            new("kn", "Kannada", "ಕನ್ನಡ"),
            new("gu", "Gujarati", "ગુજરાતી"),
            new("pa", "Punjabi", "ਪੰਜਾਬੀ"),
            new("mr", "Marathi", "मराठी"),
            new("ne", "Nepali", "नेपाली"),
            new("si", "Sinhala", "සිංහල"),
            new("my", "Burmese", "မြန်မာ"),
            new("km", "Khmer", "ខ្មែរ"),
            new("lo", "Lao", "ລາວ"),
            new("ka", "Georgian", "ქართული"),
            new("am", "Amharic", "አማርኛ"),
            new("sw", "Swahili", "Kiswahili"),
            new("zu", "Zulu", "isiZulu"),
            new("af", "Afrikaans", "Afrikaans"),
            new("sq", "Albanian", "Shqip"),
            new("az", "Azerbaijani", "Azərbaycan"),
            new("be", "Belarusian", "Беларуская"),
            new("bg", "Bulgarian", "Български"),
            new("ca", "Catalan", "Català"),
            new("hr", "Croatian", "Hrvatski"),
            new("et", "Estonian", "Eesti"),
            new("ga", "Irish", "Gaeilge"),
            new("is", "Icelandic", "Íslenska"),
            new("lv", "Latvian", "Latviešu"),
            new("lt", "Lithuanian", "Lietuvių"),
            new("mk", "Macedonian", "Македонски"),
            new("mt", "Maltese", "Malti"),
            new("sr", "Serbian", "Српски"),
            new("sk", "Slovak", "Slovenčina"),
            new("sl", "Slovenian", "Slovenščina"),
            new("eu", "Basque", "Euskara"),
            new("gl", "Galician", "Galego"),
            new("cy", "Welsh", "Cymraeg"),
            new("br", "Breton", "Brezhoneg"),
            new("gd", "Scottish Gaelic", "Gàidhlig"),
            new("lb", "Luxembourgish", "Lëtzebuergesch"),
            new("fo", "Faroese", "Føroyskt"),
            new("yi", "Yiddish", "ייִדיש"),
            new("hy", "Armenian", "Հայերեն"),
            new("kk", "Kazakh", "Қазақ"),
            new("ky", "Kyrgyz", "Кыргызча"),
            new("uz", "Uzbek", "Oʻzbek"),
            new("tg", "Tajik", "Тоҷикӣ"),
            new("mn", "Mongolian", "Монгол"),
            new("bo", "Tibetan", "བོད་སྐད་"),
            new("dz", "Dzongkha", "རྫོང་ཁ"),
            new("ms", "Malay", "Bahasa Melayu"),
            new("tl", "Filipino", "Filipino"),
            new("ceb", "Cebuano", "Cebuano"),
            new("haw", "Hawaiian", "ʻŌlelo Hawaiʻi"),
            new("mi", "Maori", "Te Reo Māori"),
            new("sm", "Samoan", "Gagana Samoa"),
            new("to", "Tongan", "Lea faka-Tonga"),
            new("fj", "Fijian", "Vosa Vakaviti"),
            new("ty", "Tahitian", "Reo Tahiti"),
            new("mg", "Malagasy", "Malagasy"),
            new("st", "Sesotho", "Sesotho"),
            new("tn", "Tswana", "Setswana"),
            new("xh", "Xhosa", "isiXhosa"),
            new("yo", "Yoruba", "Yorùbá"),
            new("ig", "Igbo", "Igbo"),
            new("ha", "Hausa", "Hausa"),
            new("so", "Somali", "Soomaali"),
            new("om", "Oromo", "Oromoo"),
            new("ti", "Tigrinya", "ትግርኛ"),
            new("rw", "Kinyarwanda", "Ikinyarwanda"),
            new("lg", "Luganda", "Luganda"),
            new("ak", "Akan", "Akan"),
            new("ff", "Fulfulde", "Fulfulde"),
            new("wo", "Wolof", "Wolof"),
            new("sn", "Shona", "ChiShona"),
            new("ny", "Chichewa", "Chichewa"),
            new("eo", "Esperanto", "Esperanto"),
            new("ia", "Interlingua", "Interlingua"),
            new("ie", "Interlingue", "Interlingue"),
            new("io", "Ido", "Ido"),
            new("vo", "Volapük", "Volapük"),
            new("la", "Latin", "Latina"),
            new("co", "Corsican", "Corsu"),
            new("sc", "Sardinian", "Sardu"),
            new("oc", "Occitan", "Occitan"),
            new("an", "Aragonese", "Aragonés"),
            new("ast", "Asturian", "Asturianu"),
            new("rm", "Romansh", "Rumantsch"),
            new("wa", "Walloon", "Walon"),
            new("pms", "Piedmontese", "Piemontèis"),
            new("vec", "Venetian", "Vèneto"),
            new("lij", "Ligurian", "Ligure"),
            new("lmo", "Lombard", "Lumbaart"),
            new("fur", "Friulian", "Furlan"),
            new("lad", "Ladino", "Ladino"),
            new("mwl", "Mirandese", "Mirandés"),
            new("ext", "Extremaduran", "Estremeñu"),
            new("mdf", "Moksha", "Мокшень"),
            new("udm", "Udmurt", "Удмурт"),
            new("kv", "Komi", "Коми"),
            new("myv", "Erzya", "Эрзянь"),
            new("cv", "Chuvash", "Чăваш"),
            new("ba", "Bashkir", "Башҡорт"),
            new("tt", "Tatar", "Татар"),
            new("sah", "Yakut", "Саха"),
            new("tyv", "Tuvan", "Тыва"),
            new("xal", "Kalmyk", "Хальмг"),
            new("bua", "Buryat", "Буряад"),
            new("ug", "Uyghur", "ئۇيغۇرچە"),
            new("tk", "Turkmen", "Türkmen"),
            new("ab", "Abkhazian", "Аҧсуа"),
            new("os", "Ossetian", "Ирон"),
            new("ce", "Chechen", "Нохчийн"),
            new("av", "Avar", "Авар"),
            new("kbd", "Kabardian", "Адыгэбзэ"),
            new("ady", "Adyghe", "Адыгэбзэ"),
            new("lez", "Lezgian", "Лезги"),
            new("inh", "Ingush", "ГӀалгӀай"),
            new("lbe", "Lak", "Лакку"),
            new("krc", "Karachay-Balkar", "Къарачай-Малкъар"),
            new("kum", "Kumyk", "Къумукъ"),
            new("nog", "Nogai", "Ногай"),
            new("crh", "Crimean Tatar", "Qırım tatar"),
            new("gag", "Gagauz", "Gagauz"),
            new("chm", "Mari", "Марий")
        };
    }

    public record LanguageInfo(string Code, string Name, string NativeName);
}
